package: ycom_fast_forward
version: 0.0.3-dev-2024-12-01
author: Alexander Walther
supportpage: https://github.com/alexplusde/ycom_fast_forward

# Benötigt `ycom`
requires:
    php: '>=8.3'
    packages:
        phpmailer: '>=2.14.0'
        ycom: '>=4.3.0'
    redaxo: '^5.18.0'

default_config:
    yform_theme: 'bootstrap5,bootstrap'
    editor: 'class="form-control redactor-editor--default"'
    first_install: '0000-00-00 00:00:00'
    mailer_profile_id: 0
    ycom_user_default_status: 0
    terms_of_use_required: 0
    default_ycom_group_id : 0
    password_rules: '{"length":{"min":10},"letter":{"min":1},"lowercase":{"min":0},"uppercase":{"min":0},"digit":{"min":1},"symbol":{"min":0}}'

page:
    title: 'translate:ycom_fast_forward.title'
    perm: admin[]
    block: ycom
    icon: rex-icon fa-fast-forward
    subpages:
        settings:
            title: 'translate:ycom_fast_forward.settings.title'
            perm: admin[]
            pjax: false
            icon: rex-icon fa-cog
        docs:
            title: 'translate:ycom_fast_forward.docs.title'
            perm: admin[]
            pjax: false
            itemClass: pull-right
            icon: rex-icon fa-info-circle
        terms_of_use:
            title: 'translate:ycom_fast_forward.terms_of_use.title'
            perm: admin[]
            pjax: false
            itemClass: pull-right text-white
            icon: rex-icon fa-file-alt
